name: the12thplayer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  kiwi: ^4.0.1
  signalr_core: ^1.1.1
  brotli: ^0.5.0
  either_option: ^1.0.6
  dio: ^4.0.0
  jiffy: ^4.1.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.1
  sleek_circular_slider: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0
  fading_edge_scrollview: ^2.0.0
  dotted_border: ^2.0.0
  snapping_sheet: ^2.0.2
  flutter_cache_manager: ^3.0.2
  image_picker: ^0.8.2
  image_cropper: ^1.4.0
  image: ^3.0.2
  auto_size_text: ^2.1.0
  tuple: ^2.0.0
  flutter_config: ^2.0.0
  sliding_up_panel: ^2.0.0+1
  pin_code_fields: ^7.1.0
  path: ^1.8.0
  better_player: ^0.0.72
  awesome_notifications: ^0.0.6+7
  # flutter_quill: ^3.9.6
  direct_select_flutter: ^1.1.1
  youtube_player_flutter: ^8.0.0
  pull_to_refresh: ^2.0.0
  ulid: ^2.0.0
  rxdart: ^0.27.3
  flutter_quill:
    git:
      url: git://github.com/singerdmx/flutter-quill.git
      ref: 949fdd76f2f6ac599777aea747faa9c96db2b694

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  kiwi_generator: ^4.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/pitch.png
    - assets/images/tshirt.png
    - assets/images/dummy_profile_image.png
    - assets/images/pre-match.png
    - assets/images/match.png
    - assets/images/post-match.png
    - assets/images/bell.gif
    - assets/images/player-card.png

  fonts:
    - family: Football
      fonts:
        - asset: assets/fonts/Football.ttf
    - family: Fifa
      fonts:
        - asset: assets/fonts/Fifa.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
